// <auto-generated />
using System;
using EtecTube.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EtecTube.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("EtecTube.Models.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChannelPicture")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Channel");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b2c9d7f-c963-483e-b1fd-30f15ad559f7"),
                            ChannelPicture = "~/img/Channels/piologo.jpg",
                            Name = "Irmãos Piologo",
                            UserId = "832a7a6c-4a57-4e9d-94af-a95c48ef4f51"
                        },
                        new
                        {
                            Id = new Guid("fd1414b0-0e39-4e3f-b2fa-4d449ab6f74c"),
                            ChannelPicture = "~/img/Channels/melodicka.jpg",
                            Name = "Melodicka Bros",
                            UserId = "832a7a6c-4a57-4e9d-94af-a95c48ef4f51"
                        },
                        new
                        {
                            Id = new Guid("f4d0b83b-6bd5-4c05-b52b-e36d774dab18"),
                            ChannelPicture = "~/img/Channels/frogleapstudios.jpg",
                            Name = "Frog Leap Studios",
                            UserId = "832a7a6c-4a57-4e9d-94af-a95c48ef4f51"
                        },
                        new
                        {
                            Id = new Guid("94895d59-e046-4478-8dec-e5ee4ec1dd5e"),
                            ChannelPicture = "~/img/Channels/99coders.jpg",
                            Name = "99 Coders",
                            UserId = "832a7a6c-4a57-4e9d-94af-a95c48ef4f51"
                        },
                        new
                        {
                            Id = new Guid("ab1f1810-a33b-4af8-a7de-3f48f62ee35e"),
                            ChannelPicture = "~/img/Channels/balta.jpg",
                            Name = "Balta.IO",
                            UserId = "832a7a6c-4a57-4e9d-94af-a95c48ef4f51"
                        });
                });

            modelBuilder.Entity("EtecTube.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("longblob");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("UserNameChangeLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = "832a7a6c-4a57-4e9d-94af-a95c48ef4f51",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b2c0e07a-f009-4cfb-b977-d21ac3292cfc",
                            Email = "admin@etectube.com.br",
                            EmailConfirmed = true,
                            FullName = "José Antonio Gallo Junior",
                            LockoutEnabled = false,
                            Nickname = "Gallo",
                            NormalizedEmail = "ADMIN@ETECTUBE.COM.BR",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEK8hUKslEce2uhx45e2l0A009wkwFXX/MBfTXMukyKdaQUQL8TJQBRaEEwwWnsqoew==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "49282936",
                            TwoFactorEnabled = false,
                            UserName = "Admin",
                            UserNameChangeLimit = 10
                        });
                });

            modelBuilder.Entity("EtecTube.Models.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(8000)
                        .HasColumnType("varchar(8000)");

                    b.Property<uint>("Dislikes")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Likes")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<uint>("Visualizations")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("Video");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d04d390-3b2c-4dc9-aad3-036faa0f16f4"),
                            ChannelId = new Guid("4b2c9d7f-c963-483e-b1fd-30f15ad559f7"),
                            Description = "VALE A PENA VER DE NOVO! Com mais de 17 milhões de views desde sua criação em 2004, este clássico da internet brasileira aparece pela primeira vez em FULL HD. É bom relembrar esse clássico, pois nesse ano de comemoração de 10 anos, vai rolar também a esperada Avaiana de Pau 2!!! Fiquem ligados!",
                            Dislikes = 0u,
                            Likes = 79000u,
                            Name = "Avaiana de Pau Edição de 10 anos em FULL HD!",
                            PublishedDate = new DateTime(2014, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Thumbnail = "~/img/Videos/avaiana_pau.png",
                            Visualizations = 2354441u
                        },
                        new
                        {
                            Id = new Guid("075753c1-9c74-4d41-9736-41bad33e7bec"),
                            ChannelId = new Guid("4b2c9d7f-c963-483e-b1fd-30f15ad559f7"),
                            Description = "Chegou a novidade que as Menines esperavam, a Avaiane de Plume, porem será que ela é tão eficaz quanto a original de Pau?",
                            Dislikes = 0u,
                            Likes = 65000u,
                            Name = "Avaiane de Plume - A Avaiane dos Mimimi",
                            PublishedDate = new DateTime(2021, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Thumbnail = "~/img/Videos/avaiana_plume.png",
                            Visualizations = 498251u
                        },
                        new
                        {
                            Id = new Guid("5a587b2b-519c-4976-bbb2-528641803d7a"),
                            ChannelId = new Guid("fd1414b0-0e39-4e3f-b2fa-4d449ab6f74c"),
                            Description = "Let's start the year with an acoustic cover of the new song Zombified by @Falling In Reverse.",
                            Dislikes = 0u,
                            Likes = 2300u,
                            Name = "Falling In Reverse - ZOMBIFIED (Acoustic Cover)",
                            PublishedDate = new DateTime(2022, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Thumbnail = "~/img/Videos/falling_reverse.png",
                            Visualizations = 25759u
                        },
                        new
                        {
                            Id = new Guid("d3e65782-70a2-4a1c-a608-e2a693f7fedd"),
                            ChannelId = new Guid("fd1414b0-0e39-4e3f-b2fa-4d449ab6f74c"),
                            Description = "What if John Denver came from a different universe to bring us some electro cyberpunk industrial synthwave sci-fi futuristic metal vibes?",
                            Dislikes = 0u,
                            Likes = 85000u,
                            Name = "Country Roads but it's CYBERPUNK/INDUSTRIAL/SCI-FI wtf",
                            PublishedDate = new DateTime(2019, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Thumbnail = "~/img/Videos/country_roads.png",
                            Visualizations = 1284517u
                        },
                        new
                        {
                            Id = new Guid("7970e8ff-6421-4c22-a010-994ef2952290"),
                            ChannelId = new Guid("f4d0b83b-6bd5-4c05-b52b-e36d774dab18"),
                            Description = "Hi there, my name is Leo and run a studio on the westside of Norway where I do music and video stuff for youtube. I also have a band called Frog Leap, where we do my metal covers live. For my covers I play everything myself as well as record, mix, master, shoot and edit the music & videos.",
                            Dislikes = 0u,
                            Likes = 101000u,
                            Name = "What Is Love (metal cover by Leo Moracchioli feat. Priscila Serrano)",
                            PublishedDate = new DateTime(2021, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Thumbnail = "~/img/Videos/what_is_love.png",
                            Visualizations = 2810254u
                        },
                        new
                        {
                            Id = new Guid("9f675999-d73d-41e2-95d9-54610aaf4f30"),
                            ChannelId = new Guid("f4d0b83b-6bd5-4c05-b52b-e36d774dab18"),
                            Description = "Hi there, my name is Leo and run a studio on the westside of Norway where I do music and video stuff for youtube. I also have a band called Frog Leap, where we do my metal covers live. For my covers I play everything myself as well as record, mix, master, shoot and edit the music & videos.",
                            Dislikes = 0u,
                            Likes = 102000u,
                            Name = "Carry On Wayward Son (metal cover by Leo Moracchioli feat. Truls Haugen)",
                            PublishedDate = new DateTime(2020, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Thumbnail = "~/img/Videos/carry_on_wayward_son.png",
                            Visualizations = 4725330u
                        },
                        new
                        {
                            Id = new Guid("c389f3b8-d7d0-4c5b-9323-4c13e44b1c5e"),
                            ChannelId = new Guid("94895d59-e046-4478-8dec-e5ee4ec1dd5e"),
                            Description = "O que acha de criarmos uma aplicação completa juntos passo a passo? É um app para compras em supermercado. Acompanhe a série de vídeos.",
                            Dislikes = 0u,
                            Likes = 186u,
                            Name = "Criando um app para compras de supermercado #07 - Finalizando o layout do app",
                            PublishedDate = new DateTime(2022, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Thumbnail = "~/img/Videos/app_delphi.png",
                            Visualizations = 1013u
                        },
                        new
                        {
                            Id = new Guid("343c045c-22c5-4df6-b40d-87837e8f37a5"),
                            ChannelId = new Guid("ab1f1810-a33b-4af8-a7de-3f48f62ee35e"),
                            Description = "String, string ou StringBuilder? Para que servem e quando devemos utilizar cada um destes tipos no C#!",
                            Dislikes = 0u,
                            Likes = 257u,
                            Name = "var, string, System.String e StringBuilder no C# | por André Baltieri #balta",
                            PublishedDate = new DateTime(2022, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Thumbnail = "~/img/Videos/balta_string.png",
                            Visualizations = 1726u
                        },
                        new
                        {
                            Id = new Guid("1243f7d1-2321-4286-be70-9c66310be574"),
                            ChannelId = new Guid("ab1f1810-a33b-4af8-a7de-3f48f62ee35e"),
                            Description = "Participe do balta.io Experience, um evento online, ao vivo e gratuito que vai reunir grandes nomes da internet em uma experiência única! https://balta.io/experience",
                            Dislikes = 0u,
                            Likes = 1000u,
                            Name = "C# 10 e .NET 6 - Novidades na manipulação de listas | por André Baltieri #balta",
                            PublishedDate = new DateTime(2021, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Thumbnail = "~/img/Videos/balta_c10.png",
                            Visualizations = 8473u
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = "832a7a6c-4a57-4e9d-94af-a95c48ef4f51",
                            ConcurrencyStamp = "43d3ca3f-7a20-4024-aae0-afe621a58970",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "cec64008-1f12-4975-b9ec-af93be7bee7b",
                            ConcurrencyStamp = "f9941b1d-cb55-447e-9c86-0ae87579ca7e",
                            Name = "Moderador",
                            NormalizedName = "MODERADOR"
                        },
                        new
                        {
                            Id = "5072cf20-3607-42e8-9d55-1ed93be32bb7",
                            ConcurrencyStamp = "1afb8c98-449b-48a3-b3d4-b85c013aacc6",
                            Name = "Usuario",
                            NormalizedName = "USUARIO"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "832a7a6c-4a57-4e9d-94af-a95c48ef4f51",
                            RoleId = "832a7a6c-4a57-4e9d-94af-a95c48ef4f51"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("EtecTube.Models.Channel", b =>
                {
                    b.HasOne("EtecTube.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EtecTube.Models.Video", b =>
                {
                    b.HasOne("EtecTube.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EtecTube.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EtecTube.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtecTube.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EtecTube.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
